# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master

  uses: google-github-actions/deploy-appengine@v0.4.0
  with:
    # The GCP project ID. Overrides project ID set by credentials.
    project_id: ${{ gcloud_helloworld.GCP_PROJECT_ID }}
    credentials: ${{ gcloud_helloworld.GCP_PRIVATE_KEY }}
